export const copy = {
  nav: {
    home: "Home",
    photos: "Photos",
    growth: "Growth",
    history: "History",
    books: "Books",
    sameAge: "Same age",
    activities: "Activities",
    chat: "Chat",
    more: "More",
    add: "Add",
    account: "Account",
  },
  account: {
    signedInAs: "Signed in as",
    tags: "Tags",
    faceReview: "Face review",
    settings: "Settings",
    importExport: "Import/Export",
    admin: "Admin",
    logOut: "Log out",
  },
  moreSheet: {
    title: "More",
    blurbs: {
      history: "Everything, day by day",
      books: "Turn memories into a story",
      sameAge: "Compare everyone at the same age",
      activities: "Seasons, meets and results",
      chat: "Family messages",
    } as Record<string, string>,
  },
  addSheet: {
    title: "Add",
    whoFor: "Who is this for?",
    photos: "Photos",
    measurement: "Measurement",
    milestone: "Milestone",
    close: "Close",
  },
  when: {
    label: "When",
    today: "Today",
    yesterday: "Yesterday",
    pickDate: "Pick a date…",
    byAge: "By age…",
    date: "Date",
    years: "Age in years",
    months: "and months",
  },
  measurement: {
    title: "Measurement",
    who: "Who was measured?",
    height: "Height",
    weight: "Weight",
    heightUnit: "Height unit",
    weightUnit: "Weight unit",
    feet: "Feet",
    inches: "Inches",
    pounds: "Pounds",
    ounces: "Ounces",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    pickPerson: "Pick who was measured",
  },
  milestone: {
    title: "Milestone",
    who: "Who is this about?",
    whatHappened: "What happened?",
    placeholder: "Wrote her name for the first time",
    whatTheySaid: "What did they say?",
    quotePlaceholder: "The moon is following our car!",
    context: "Context (optional)",
    contextPlaceholder: "On the drive home from Grandma's",
    whatTheyMade: "What did they make?",
    artworkPlaceholder: "Drew the whole family as dinosaurs",
    artworkPhotos: "Photos of it",
    addArtworkPhoto: "Add a photo of it",
    uploadingArtworkPhoto: "Uploading…",
    category: "Category",
    more: "Add photos / tags",
    photos: "Photos",
    tags: "Tags",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    pickPerson: "Pick who this is about",
    needsText: "Say what happened",
  },
  photos: {
    title: "Photos",
    choose: "Choose photos",
    addMore: "Add more",
    whoIsIn: "Who's in these?",
    caption: "Caption",
    captionPlaceholder: "Optional",
    tags: "Tags",
    taken: "Taken",
    change: "change",
    done: "Done",
    finishing: "Saving…",
    uploading: "Uploading",
    uploaded: "Uploaded",
    failed: "Failed",
    dropHint: "or drop them here",
  },
  home: {
    seeAll: "See all",
    history: "History",
    addPerson: "Add family member",
    inSeason: "In season",
    onThisDay: "On this day",
    recent: "Recent",
    nothingRecent: "Nothing added in the last two weeks.",
    dismiss: "Dismiss",
    checkup: "measured",
    checkupTitle: "Measured",
    addPhotos: "Add photos",
    addResults: "Add results",
    turned: (name: string, age: number) => `${name} turned ${age}`,
    photoCount: (n: number) => (n === 1 ? "1 photo" : `${n} photos`),
    yearsAgo: (n: number) => (n === 1 ? "1 year ago" : `${n} years ago`),
    eventTiming: { now: "Today", next: "Next", last: "Last" } as Record<string, string>,
  },
  result: "Result",
  sameAge: {
    title: "Same age",
    intro: "Explore photos, milestones and measurements from similar ages.",
    recordedAges: "Browse ages with records",
    sliderHelp: "Each slider position is an age with saved records.",
    loading: "Loading records…",
    retry: "Try again",
    youngerWithRecords: "Younger age with records",
    olderWithRecords: "Older age with records",
    peopleWithRecords: (n: number) => `${n} ${n === 1 ? "person has" : "people have"} records`,
    onlyOne: "Try another age to compare more people.",
    missingRecords: (n: number) =>
      `${n} other ${n === 1 ? "person has" : "people have"} no records near this age.`,
    noSavedRecords:
      "No photos, milestones or measurements to compare yet. Add records to a family member’s profile to get started.",
    nothingAtAge: "No saved records near this age. Choose an age with records above.",
    at: "At",
    older: "Older",
    younger: "Younger",
    now: "now",
    noRecords: "no records at this age",
    seeAll: "See everything at this age →",
    nobodyElse: "Nobody else has anything from this age yet.",
    atThisAge: (age: string) => (age === "Newborn" ? "At birth" : `At ${age}`),
    empty: "Add birthdays to compare everyone at the same age.",
    sideBySide: "Side by side",
    viewPhoto: "View photo",
    noPhoto: (names: string) => `No photo near this age: ${names}`,
    anotherPhoto: "Another photo",
  },
  milestoneDetail: {
    back: "Back",
    edit: "Edit",
    delete: "Delete",
    confirmDelete: (text: string) => `Delete this milestone: "${text}"?`,
    notFound: "That milestone could not be found.",
    atAge: (age: string) => `at ${age}`,
  },
  person: {
    tabs: {
      story: "Story",
      quotes: "Quotes",
      artwork: "Artwork",
      photos: "Photos",
      growth: "Growth",
      activities: "Activities",
    },
    born: (date: string) => `born ${date}`,
    measured: (ago: string) => `Measured ${ago}`,
    siblingThen: (name: string, value: string) => `${name} was ${value} at this age`,
    entries: (n: number) => (n === 1 ? "1 entry" : `${n} entries`),
    next: (event: string) => `next: ${event}`,
    nothingYet: (name: string) => `Nothing recorded for ${name} yet. Use + to add something.`,
    noPhotos: "No photos yet.",
    noQuotes: (name: string) => `No quotes from ${name} yet.`,
    noArtwork: (name: string) => `No artwork from ${name} yet.`,
    growingUp: "Growing up",
    seeGrowingUp: "See the full timeline →",
    oftenWith: "Often photographed with",
    openInPhotos: "Open in Photos →",
    metric: "Measurement",
    showSiblings: "Show siblings",
    measure: "Measure",
    noMeasurements: "No measurements of this kind yet.",
  },
  history: {
    people: "People",
    more: "More",
    show: "Show",
    tags: "Tags",
    manageTags: "Manage tags →",
    clear: "Clear",
    search: "Search milestones",
    searchPlaceholder: "Search milestones",
    years: "Jump to year",
    empty: "Nothing recorded yet. Use + to add the first thing.",
    noMatches: "Nothing matches these filters.",
    loadYear: (year: number) => `Load ${year}`,
    resultsFor: (query: string, n: number) =>
      `${n === 1 ? "1 milestone" : `${n} milestones`} matching "${query}"`,
    types: {
      milestones: "Milestones",
      measurements: "Measurements",
      photos: "Photos",
      activities: "Activities",
      birthdays: "Birthdays",
    },
  },
  ageChart: {
    zoomHint: "Drag across the chart to zoom",
    resetZoom: "Reset zoom",
  },
  growthPage: {
    title: "Growth",
    people: "People",
    metric: "Measurement",
    bands: "Percentile bands",
    bandsOff: "Off",
    girls: "Girls",
    boys: "Boys",
    measure: "Measure",
    empty: "Pick people with measurements to see them here.",
    noData: "No measurements yet.",
  },
};
