export const copy = {
  nav: {
    home: "Home",
    photos: "Photos",
    growth: "Growth",
    history: "History",
    chat: "Chat",
    add: "Add",
    account: "Account",
  },
  account: {
    signedInAs: "Signed in as",
    activities: "Activities",
    tags: "Tags",
    faceReview: "Face review",
    settings: "Settings",
    importExport: "Import/Export",
    admin: "Admin",
    logOut: "Log out",
  },
  addSheet: {
    title: "Add",
    whoFor: "Who is this for?",
    photos: "Photos",
    measurement: "Measurement",
    milestone: "Milestone",
    close: "Close",
  },
  when: {
    label: "When",
    today: "Today",
    yesterday: "Yesterday",
    pickDate: "Pick a date…",
    byAge: "By age…",
    date: "Date",
    years: "Age in years",
    months: "and months",
  },
  measurement: {
    title: "Measurement",
    who: "Who was measured?",
    height: "Height",
    weight: "Weight",
    heightUnit: "Height unit",
    weightUnit: "Weight unit",
    feet: "Feet",
    inches: "Inches",
    pounds: "Pounds",
    ounces: "Ounces",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    pickPerson: "Pick who was measured",
  },
  milestone: {
    title: "Milestone",
    who: "Who is this about?",
    whatHappened: "What happened?",
    placeholder: "Wrote her name for the first time",
    category: "Category",
    more: "Add photos / tags",
    photos: "Photos",
    tags: "Tags",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    pickPerson: "Pick who this is about",
    needsText: "Say what happened",
  },
  photos: {
    title: "Photos",
    choose: "Choose photos",
    addMore: "Add more",
    whoIsIn: "Who's in these?",
    caption: "Caption",
    captionPlaceholder: "Optional",
    tags: "Tags",
    taken: "Taken",
    change: "change",
    done: "Done",
    finishing: "Saving…",
    uploading: "Uploading",
    uploaded: "Uploaded",
    failed: "Failed",
    dropHint: "or drop them here",
  },
};
