name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Go dependencies
        run: go mod download

      - name: Create minimal dist for Go embed
        run: |
          mkdir -p release/dist
          echo '<!DOCTYPE html><html><body>CI Build</body></html>' > release/dist/index.html
          echo 'console.log("CI build");' > release/dist/main.js

      - name: Run tests
        run: make test

      - name: Build Go binary only
        run: make build-go
